apiVersion: v2
name: matriculaaa
description: A Helm chart to deploy the matriculaAA project on Kubernetes.
type: application
version: 0.1.0
keywords:
- matriculaaa
home: http://github.com/leomichalski/matriculaAA
maintainers:
- name: leomichalski
- email: leonardomichalskim@gmail.com
kubeVersion: ">=1.22.0-0"
dependencies:
- name: strimzi-kafka-operator
  version: "0.38.0"
  repository: "https://strimzi.io/charts"
  condition: detectorDeVagas.enabled
- name: ingress-nginx
  version: 4.8.2
  repository: https://kubernetes.github.io/ingress-nginx
  condition: externalAccess.enabled
- name: prometheus
  version: 25.3.1
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
