apiVersion: v2
name: matriculaaa
description: A Helm chart to deploy the matriculaAA project on Kubernetes.
type: application
version: 0.1.0
keywords:
  - matriculaaa
home: http://github.com/leomichalski/matriculaAA
maintainers:
  - name: leomichalski
    email: leonardomichalskim@gmail.com
