debug: false
namespace: matriculaaa

django:
  enabled: true
  container:
    imagePullPolicy: Always
    image: api_production_django
    tag: latest
    requests:
      cpu: 100m
      memory: 60Mi
    limits:
      cpu: 500m
      memory: 500Mi
    port: 5000

  replicas: 3
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

  # TODO: use External Secrets Operator with AWS Secrets Manager
  server_name: 
  secret_key: 
  superuser:
    password: 
    email: 

postgres:
  db: 
  host: 
  password: 
  port: 
  user: 
