# Generated by Django 4.2 on 2023-09-13 02:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('matricula', models.IntegerField(verbose_name='matricula')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
                ('cpf', models.BigIntegerField(unique=True, verbose_name='CPF')),
                ('data_de_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('turmas_desejadas', models.ManyToManyField(related_name='discentes_interessados', to='turmas.turma', verbose_name='turmas desejadas')),
            ],
            options={
                'verbose_name': 'discente',
                'verbose_name_plural': 'discentes',
                'ordering': ('email',),
            },
        ),
    ]
