# TODO: create secret with External Secrets Operator
{{- if .Values.django.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: django
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ required "A valid .Values.django.secret_key entry required!" .Values.django.secret_key | quote }}
  SUPERUSER_EMAIL: {{ required "A valid .Values.django.superuser.email entry required!" .Values.django.superuser.email | quote }}
  SUPERUSER_PASSWORD: {{ required "A valid .Values.django.superuser.password entry required!" .Values.django.superuser.password | quote }}
{{- end }}
