{{- if .Values.django.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: django
  ports:
  - name: django
    protocol: TCP
    port: {{ .Values.django.service.port }}
    targetPort: {{ .Values.django.container.port }}
  {{- if (not .Values.externalAccess.enabled) }}
    nodePort: 31000
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
{{- end }}
