# TODO: allow existing secret to be used
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ required "A valid .Values.postgres.db entry required!" .Values.postgres.db | quote }}
  POSTGRES_HOST: {{ required "A valid .Values.postgres.host entry required!" .Values.postgres.host | quote }}
  POSTGRES_PASSWORD: {{ required "A valid .Values.postgres.password entry required!" .Values.postgres.password | quote }}
  POSTGRES_PORT: {{ required "A valid .Values.postgres.port entry required!" .Values.postgres.port | quote }}
  POSTGRES_USER: {{ required "A valid .Values.postgres.user entry required!" .Values.postgres.user | quote }}
