# TODO: use strimzi KafkaTopic instead
{{- if .Values.detectorDeVagas.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topic-vaga-disponivel
data:
  KAFKA_TOPIC_VAGA_DISPONIVEL: {{ required "A valid .Values.kafkaTopicName entry required!" .Values.kafkaTopicName | quote }}
{{- end }}
