#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py loaddata todos_os_departamentos.json

# create super user if not exists
cat <<EOF | python manage.py shell
from django.contrib.auth import get_user_model

User = get_user_model()

if not User.objects.filter(email="$SUPERUSER_EMAIL").exists():
    User.objects.create_superuser("$SUPERUSER_EMAIL", "$SUPERUSER_PASSWORD")
else:
    print('User "{}" exists already, not created'.format("$SUPERUSER_EMAIL"))
EOF

exec python manage.py runserver 0.0.0.0:8000
